### ISSUE TITLE
Results not in html

### ISSUE THREAD

**Issue by NikitaSheff** [Smoliarick/cypress-discord-webhook-integration#1]
Hey!
Can you provide sending report results not is html format? Because discord can't open html files within it
May be in jpeg format or text file?
something like that
![image](https://github.com/Smoliarick/cypress-discord-webhook-integration/assets/99482593/7f7fb9d7-19ad-4b87-b26e-c9a1e6af9518)

**Comment by Smoliarick** [comment]
> Hey! Can you provide sending report results not is html format? Because discord can't open html files within it May be in jpeg format or text file? something like that ![image](https://user-images.githubusercontent.com/99482593/262369511-7f7fb9d7-19ad-4b87-b26e-c9a1e6af9518.png)

Hi! I've updated package to new version -> 1.1.1. I've added new functionality which helps you convert html reports to PNG files. Just add 'true' value as the last param in the function:

```js
await sendToDiscordWebhook(
  webhookURL,     // required variable
  files,          // required variable
  undefined,      // set to undefined if you don't use custom message, but use custom avatar, custom username or convertHtmlToPng functionality
  undefined,      // set to undefined if you don't use custom username, but use custom avatar or convertHtmlToPng functionality
  undefined,      // set to undefined if you don't use custom message, but use convertHtmlToPng functionality
  true,           // if you want to convert HTML files to PNG set it as true, or remove it if you don't want to use this functionality
);
```

![image](https://github.com/Smoliarick/cypress-discord-webhook-integration/assets/104084410/189cca88-9a64-4ceb-ae2a-8e5da7e0e7a1)

Also, I've updated repo with example: https://github.com/Smoliarick/cypress-discord-webhook-integration-example#how-to-run-new-feature-for-converting-html-files-to-png-files

Please, let me know if it works for you, I will close this issue!

**Comment by NikitaSheff** [comment]
I have successfully implemented new feature to my project, thank you!

**Comment by NikitaSheff** [comment]
@Smoliarick Hi! Maybe there is a way to optimize .png files if there are a lot of tests? or maybe divide them into several pictures?
![image](https://github.com/Smoliarick/cypress-discord-webhook-integration/assets/99482593/9ee4a9df-ec9f-47d9-b844-487fa7c9b62c)

**Comment by Smoliarick** [comment]
@NikitaSheff You can click on the PNG file and click on the Open in Browser button in preview. After it, you can see all results in browser using zoom in/out. Or download this file and use zoom in/out functionality in your app for images.

![image](https://github.com/Smoliarick/cypress-discord-webhook-integration/assets/104084410/904136c5-af9a-4d16-9405-7116ee645d2e)
![image](https://github.com/Smoliarick/cypress-discord-webhook-integration/assets/104084410/5b676e47-e2ff-4328-90b7-067a393be114)

Discord supports only 10 files per message, and PNG image is generated using HTML report from https://www.npmjs.com/package/cypress-mochawesome-reporter. If it's possible to divide HTML report per sections, maybe it will be possible to send separate images for each section. Need to investigate it.

**Comment by NikitaSheff** [comment]
@Smoliarick yeah, I see that I can open image using browser but it would be much more convenient to look at the image without having to zoom in it. Thanks

**Comment by Smoliarick** [comment]
@NikitaSheff I will check, if it's possible to create separate images, will add this feature later

**Comment by Smoliarick** [comment]
@NikitaSheff I've found workaround for you. You can add all settings into the 'after:spec' function instead of 'after:run'. For example:

```js
on('after:spec', async (results) => {
        await afterRunHook();

        // --------------------required part------------------------------
        const sendToDiscordWebhook = require('cypress-discord-webhook-integration'); // import lib
        const webhookURL = process.env.WEBHOOK_URL; // REQUIRED: Webhook URL for Discord
        const files = ['./cypress/reports/html/index.html']; // REQUIRED: File paths
        // --------------------required part------------------------------

        // --------------------custom data------------------------------
        const customUsername = 'Custom Username for Bot'; // Custom name for Bot's username in Discord
        const customMessage = 'Custom message for Bot'; // Custom message for Bot's message in Discord
        const customAvatar = 'https://cdn.sanity.io/images/o0o2tn5x/production/13b9c8412093e2f0cdb5495e1f59144967fa1664-512x512.jpg'; // Custom avatar URL for Bot in Discord
        // --------------------custom data------------------------------

        // --------------------required part------------------------------
        // Using function
        await sendToDiscordWebhook(
          webhookURL,     // required variable
          files,          // required variable
          customMessage,  // set to undefined if you don't use custom message, but use custom avatar, custom username or convertHtmlToPng functionality
          customUsername, // set to undefined if you don't use custom username, but use custom avatar or convertHtmlToPng functionality
          customAvatar,   // set to undefined if you don't use custom message, but use convertHtmlToPng functionality
          true,           // if you want to convert HTML files to PNG set it as true, or remove it if you don't want to use this functionality
        );
        // --------------------required part------------------------------
      });
```

Please, also update your package version to the latest version. I've made a little update to function, it helps you to use it with 'after:spec' function. After it, image with report will be sent after each spec.

**Comment by NikitaSheff** [comment]
@Smoliarick Thank you for you advise
Perhaps there is a way to combine all the pictures into one message that the bot will send to my chat.? 
Because with this solution I receive 10 messages - that's to much :)

**Comment by Smoliarick** [comment]
@NikitaSheff I've added new functions for sending 1 message with 10 or less results for PNG images. Please, update your package to the latest version and use this way:

```js
// Add the next line at the beginning of the file
const { sendToDiscordWebhookForEachSpec, afterSpecFunction } = require('cypress-discord-webhook-integration'); // import lib

// Add the next lines into the setupNodeEvents function
on('after:spec', async (results) => {
  await afterRunHook();

  await afterSpecFunction('./cypress/reports/html/index.html');
});

on('after:run', async (results) => {
  // --------------------required part------------------------------
  const webhookURL = process.env.WEBHOOK_URL; // REQUIRED: Webhook URL for Discord
  // --------------------required part------------------------------

  // --------------------custom data------------------------------
  const customUsername = 'Custom Username for Bot'; // Custom name for Bot's username in Discord
  const customMessage = 'Custom message for Bot'; // Custom message for Bot's message in Discord
  const customAvatar = 'https://cdn.sanity.io/images/o0o2tn5x/production/13b9c8412093e2f0cdb5495e1f59144967fa1664-512x512.jpg'; // Custom avatar URL for Bot in Discord
  // --------------------custom data------------------------------

  // --------------------required part------------------------------
  // Using function
  await sendToDiscordWebhookForEachSpec(
    webhookURL,     // required variable
    customMessage,  // set to undefined if you don't use custom message, but use custom avatar, custom username functionality
    customUsername, // set to undefined if you don't use custom username, but use custom avatar functionality
    customAvatar,   // set to undefined if you don't use custom message
  );
  // --------------------required part------------------------------
});
```
