### ISSUE TITLE
Add compatibility with Cypress v13

### ISSUE THREAD

**Issue by NikitaSheff** [Smoliarick/cypress-discord-webhook-integration#2]
Hi
Your plugin doesn't work if I update Cypress to v13

**Comment by Smoliarick** [comment]
Hi! It doesn't relate to plugin, update [cypress-mochawesome-reporter](https://www.npmjs.com/package/cypress-mochawesome-reporter/v/3.6.0) to the last version. I've checked v.13.3.0 Cypress + v.3.6.0 cypress-mochawesome-reporter and it works well.

**Comment by NikitaSheff** [comment]
Thanks, I'll try to update cypress-mochawesome-reporter

**Comment by NikitaSheff** [comment]
@Smoliarick I observe current behavior 
![image](https://github.com/Smoliarick/cypress-discord-webhook-integration/assets/99482593/72d9f048-f5e8-47f0-bf53-447f8963080c)

Packages:
  Cypress v13.3.0
 "cypress-mochawesome-reporter": "^3.6.0"
  "cypress-discord-webhook-integration": "^1.2.1"

**Comment by Smoliarick** [comment]
@NikitaSheff Did you import it?:
`const { sendToDiscordWebhook } = require('cypress-discord-webhook-integration'); // import lib`

**Comment by NikitaSheff** [comment]
> @NikitaSheff Did you import it?: `const { sendToDiscordWebhook } = require('cypress-discord-webhook-integration'); // import lib`

Yes thanks, I also needed to update the config files because you made some updates to your code. :)

**Comment by NikitaSheff** [comment]
@Smoliarick I have a new issue while running tests

My config file:
`const {defineConfig} = require("cypress");`
`const {beforeRunHook, afterRunHook} = require('cypress-mochawesome-reporter/lib');`
`const {sendToDiscordWebhookForEachSpec, afterSpecFunction} = require('cypress-discord-webhook-integration'); // import lib`
`const {sendToDiscordWebhook} = require('cypress-discord-webhook-integration')`
`require('dotenv').config();`
![image](https://github.com/Smoliarick/cypress-discord-webhook-integration/assets/99482593/e5333d81-a63a-404a-a953-60417b5dd492)

And test's logs:
![image](https://github.com/Smoliarick/cypress-discord-webhook-integration/assets/99482593/0d3ac17c-4c0d-446f-8c5d-2cb9172aa49d)

"cypress": "^13.3.0",
"cypress-mochawesome-reporter": "^3.6.0"

Do you have any ideas?
Thanks

**Comment by Smoliarick** [comment]
You forgot beforeRunHook function from reporter lib:
```js
on('before:run', async (details) => {
    await beforeRunHook(details);
});
```

**Comment by NikitaSheff** [comment]
@Smoliarick Ok, thanks!
Can you add this code to your instruction?

**Comment by Smoliarick** [comment]
I left `await afterRunHook();` because it was in function where I set up my package (because of the copy-paste from my code)

**Comment by NikitaSheff** [comment]
Thank you!
